### ISSUE TITLE
Ignore deleted files

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/kwalitee#63]
It seems that removed files are also checked for kwalitee:

http://kwalitee.invenio-software.org/inveniosoftware/invenio/branches/f32fe2e25165ba559fd22d6c0bf75b7aa74615b1/lnielsen:master-datacite

and 

https://github.com/inveniosoftware/invenio/pull/2934/files

**Comment by jirikuncar** [comment]
Deployed version with "old" fix https://github.com/inveniosoftware/kwalitee/commit/6d3e9a6ac5861ce1a66839d5c116ff81f628f410.
