### ISSUE TITLE
import order checking: flake8 -> isort

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/kwalitee#79]
`kwalitee` is currently using `flake8-import-order` to check the order of import statements.  This produces different ordering than `isort`.  As we discussed in https://github.com/inveniosoftware/claimstore/issues/33 and elsewhere, we plan to migrate fully to `isort`, and ideally centralise all checks to `pytest`, using `pytest-isort`, so that one could use:

```console
$ cat pytest.ini
[pytest]
addopts = --pep8 --pep257 --isort --ignore=docs --cov=mypackage --cov-report=term-missing tests mypackage
```

Consequently, `kwalitee` should rely on `isort` rather than `flake8-import-order`.

**Comment by jirikuncar** [comment]
Closed via 2f4fb0d8
