### ISSUE TITLE
setup: offer simple CLI mode installation

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/kwalitee#80]
Sometimes it is wanted to plug `kwalitee` message format checking to the usual Travis CI build process, instead of setting the kwalitee as an external service that only comments on PRs.  (An advantage being that developers see immediately green/red light for their PRs.)  Here is one example of such a setup:

- https://github.com/inveniosoftware/claimstore/blob/master/.travis.yml

This works, but is kind of unnecessarily heavy, because kwalitee installs Flask and SQLAlchemy and whatnot by default, which is not needed in this case.

It'll be useful to offer a sort of minimal installation target in `setup.py` that will install kwalitee with standalone minimal requirements only in mind, allowing it to run in CLI, without any full-fledged back-end support.  E.g. `cli` installation target, different from `server` installation target.  (with default being CLI, which seems to be more common use case)

**Comment by greut** [comment]
It probably means moving away from Flask-Script to use click instead.

**Comment by jirikuncar** [comment]
> It probably means moving away from Flask-Script to use click instead.

:+1:

**Comment by jirikuncar** [comment]
Closed via 2f4fb0d8
