### ISSUE TITLE
authors: invalid encoding

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/kwalitee#87]
`kwalitee check authors` - inveniosoftware/invenio-communities@dae341c26f681fb82a77ce6f59dee24967a87de7

--
```python
author = u'{0.author} <{0.author.email}>'.format(commit).encode('utf-8')
```

**Comment by tiborsimko** [comment]
Good catch. I have spotted one more UTF-8 issue when emitting messages, PR follows.
